"""empty message

Revision ID: 15ba83512fec
Revises: 892dbdb1d9b0
Create Date: 2018-07-30 01:38:04.663910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ba83512fec'
down_revision = '892dbdb1d9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'feed', 'user', ['user_id'], ['id'])
    op.add_column('post', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'votes')
    op.drop_constraint(None, 'feed', type_='foreignkey')
    # ### end Alembic commands ###
