"""empty message

Revision ID: 27630d92b728
Revises: a4702859796a
Create Date: 2018-06-27 10:13:29.576559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27630d92b728'
down_revision = 'a4702859796a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'domain')
    # ### end Alembic commands ###
