"""empty message

Revision ID: 892dbdb1d9b0
Revises: be3f72eab62d
Create Date: 2018-07-08 21:19:02.966062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892dbdb1d9b0'
down_revision = 'be3f72eab62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'location')
    # ### end Alembic commands ###
