"""empty message

Revision ID: 90e6d7684eef
Revises: b510973ced08
Create Date: 2018-07-01 09:35:15.572807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e6d7684eef'
down_revision = '3872d2c85f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('depth', sa.Integer(), nullable=True,
                                       default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'depth')
    # ### end Alembic commands ###
