"""empty message

Revision ID: b510973ced08
Revises: 07105363599f
Create Date: 2018-06-29 18:39:23.560569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b510973ced08"
down_revision = "07105363599f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("role", sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
