"""empty message

Revision ID: fbfec56d097e
Revises: 3b1f45ed96c7
Create Date: 2018-06-27 10:04:50.000959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfec56d097e'
down_revision = '3b1f45ed96c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'date')
    # ### end Alembic commands ###
